### PR TITLE
Fixes #8, fixes #6, fixes #5

### LINKED ISSUE #5: Replace full paths with relative paths inside the repository
Currently, there are full paths used in the .ipynb so this issue aims to replace all full paths with relative paths.

Tasks:
- Identify all instances of full paths in the repository.
- Replace them with relative paths.
- Test to ensure that all functionalities are working as expected after the changes.

### LINKED ISSUE #6: Pull code into a .py Python file
Currently all code is in a python notebook. Pull code from the notebook into a python file(s) and ensure that it yields the same output.

### LINKED ISSUE #8: Refactor monolithic code into bite-sized functions

### PR DESCRIPTION
**Pull request by KaurMahima**

### CODE REVIEW

**Comment by gilmourj** [comment]
Mahima, Michelle, and I discussed and I will make some changes to this for organizational structure.

**Comment by gilmourj** [comment]
@audiracmichelle I added functionality to run this on the command line and reorganized the structure. The user can specify input data and output locations, along with the time period. Since I've made changes here, I wanted to add you as a reviewer. @KaurMahima would appreciate your thoughts on this functionality as well!

**Comment by gilmourj** [comment]
Reverted last commit as daily analysis is not yet ready, per conversation with @KaurMahima.

**Review by audiracmichelle — APPROVED** [review]
I am a bit unsure of what are the arguments the user is expected to pass to main, but this is fine if this is later explained in the README

**Pull request merged**
